create table if not exists public.profiles (
  id text primary key,
  email text not null unique,
  name text not null,
  role text not null default 'Team Member',
  status text not null default 'Activated',
  department text,
  title text,
  phone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.companies (
  id text primary key,
  name text not null,
  industry text,
  status text,
  website text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.teams (
  id text primary key,
  name text not null,
  department text,
  lead_id text references public.profiles(id) on delete set null,
  status text not null default 'Active',
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.meetings (
  id text primary key,
  ref text not null unique,
  title text not null,
  company_id text references public.companies(id) on delete set null,
  company_name text,
  team_id text references public.teams(id) on delete set null,
  department text,
  date date not null,
  start_time time,
  end_time time,
  status text not null default 'Scheduled',
  type text not null default 'Virtual',
  responsible_id text references public.profiles(id) on delete set null,
  created_by text references public.profiles(id) on delete set null,
  agenda text,
  notes text,
  decisions text,
  action_items_text text,
  remarks text,
  reschedule_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.meetings add column if not exists location text;
alter table public.meetings add column if not exists meeting_link text;

create table if not exists public.meeting_participants (
  meeting_id text not null references public.meetings(id) on delete cascade,
  user_id text not null references public.profiles(id) on delete cascade,
  participant_type text not null default 'Team Member',
  primary key (meeting_id, user_id)
);

create table if not exists public.action_items (
  id text primary key,
  meeting_id text references public.meetings(id) on delete set null,
  company_id text references public.companies(id) on delete set null,
  title text not null,
  description text,
  status text not null default 'To Do',
  priority text not null default 'Medium',
  assignee_id text references public.profiles(id) on delete set null,
  due_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.documents (
  id text primary key,
  meeting_id text references public.meetings(id) on delete cascade,
  company_id text references public.companies(id) on delete cascade,
  name text not null,
  type text,
  size_bytes bigint,
  storage_path text,
  metadata jsonb not null default '{}'::jsonb,
  created_by text references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id text primary key,
  user_id text references public.profiles(id) on delete cascade,
  type text not null default 'system',
  title text not null,
  message text,
  meeting_id text references public.meetings(id) on delete cascade,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.workspace_settings (
  id text primary key default 'default',
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.meeting_email_queue (
  id bigint generated by default as identity primary key,
  meeting_id text not null references public.meetings(id) on delete cascade,
  recipients jsonb not null,
  subject text not null,
  body text not null,
  status text not null default 'pending' check (status in ('pending', 'sent', 'failed')),
  provider_message_id text,
  error_message text,
  created_at timestamptz not null default now(),
  sent_at timestamptz
);

create index if not exists meetings_date_idx on public.meetings(date, start_time);
create index if not exists meeting_participants_user_idx on public.meeting_participants(user_id);
create index if not exists notifications_user_read_idx on public.notifications(user_id, read, created_at desc);
create index if not exists email_queue_status_idx on public.meeting_email_queue(status, created_at);

alter table public.profiles enable row level security;
alter table public.companies enable row level security;
alter table public.teams enable row level security;
alter table public.meetings enable row level security;
alter table public.meeting_participants enable row level security;
alter table public.action_items enable row level security;
alter table public.documents enable row level security;
alter table public.notifications enable row level security;
alter table public.workspace_settings enable row level security;
alter table public.meeting_email_queue enable row level security;

drop policy if exists "Public can read meetings" on public.meetings;
create policy "Public can read meetings" on public.meetings
  for select to anon, authenticated using (true);

drop policy if exists "Public can read meeting participants" on public.meeting_participants;
create policy "Public can read meeting participants" on public.meeting_participants
  for select to anon, authenticated using (true);

drop policy if exists "Private profiles" on public.profiles;
create policy "Private profiles" on public.profiles
  for all to anon, authenticated using (false) with check (false);

drop policy if exists "Private companies" on public.companies;
create policy "Private companies" on public.companies
  for all to anon, authenticated using (false) with check (false);

drop policy if exists "Private teams" on public.teams;
create policy "Private teams" on public.teams
  for all to anon, authenticated using (false) with check (false);

drop policy if exists "Private action items" on public.action_items;
create policy "Private action items" on public.action_items
  for all to anon, authenticated using (false) with check (false);

drop policy if exists "Private documents" on public.documents;
create policy "Private documents" on public.documents
  for all to anon, authenticated using (false) with check (false);

drop policy if exists "Private notifications" on public.notifications;
create policy "Private notifications" on public.notifications
  for all to anon, authenticated using (false) with check (false);

drop policy if exists "Private workspace settings" on public.workspace_settings;
create policy "Private workspace settings" on public.workspace_settings
  for all to anon, authenticated using (false) with check (false);

drop policy if exists "Private email queue" on public.meeting_email_queue;
create policy "Private email queue" on public.meeting_email_queue
  for all to anon, authenticated using (false) with check (false);

revoke all on public.meeting_email_queue from anon, authenticated;
revoke all on public.workspace_settings from anon, authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'meetings'
  ) then
    alter publication supabase_realtime add table public.meetings;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'meeting_participants'
  ) then
    alter publication supabase_realtime add table public.meeting_participants;
  end if;
end $$;